### ISSUE TITLE
Syntax error in version file

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/4ksp_Expanded#2]
After 8ca30b1042d4bbf00ce4b9c9435349662f8f6bb7, these `}` characters are duplicative:

https://github.com/linuxgurugamer/4ksp_Expanded/blob/8ca30b1042d4bbf00ce4b9c9435349662f8f6bb7/4kSP.version#L20-L21

This is preventing this mod's current release from being added to CKAN.

**Comment by linuxgurugamer** [comment]
Thanks, I'll get it fixed
